/// Category of a chemical element
#[derive(Copy, Clone, PartialEq)]
pub enum Category {
    AlkaliMetal,
    AlkalineEarthMetal,
    TransitionMetal,
    PostTransitionMetal,
    Metalloid,
    PolyatomicNonmetal,
    DiatomicNonmetal,
    NobleGas,
    Lanthanide,
    Actinide,
    Unknown,
}

/// The possible states of matter of a chemical element
#[derive(Copy, Clone, PartialEq)]
pub enum State {
    Solid,
    Liquid,
    Gas,
    Plasma,
    Unknown,
}

/// Represents the position of a chemical element on the periodic table, using
/// the 18-column layout
#[derive(Copy, Clone)]
pub enum Position {
    MainTable { period: u32, group: u32 },
    Lanthanides { column: u32 },
    Actinides { column: u32 },
}

/// Represents a chemical element
pub struct Element {
    pub atomic_number: i32,
    /// The English name of the element
    pub name: &'static str,
    /// The symbol of the element
    pub symbol: &'static str,
    /// The category of the element
    pub category: Category,
    /// Position on the periodic table
    pub position: Position,
    /// Standard atomic weight, rounded to 3 decimal digits
    pub weight: Option<f32>,
    /// State of the element at standard conditions for temperature and pressure
    pub state: State,
}

/// The list of chemical elements
/// Data mostly taken from:
/// https://en.wikipedia.org/wiki/List_of_chemical_elements
pub static ELEMENTS: [Element; 118] = [
    Element {
        atomic_number: 1,
        name: "Hydrogen",
        symbol: "H",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 1, group: 1 },
        weight: Some(1.008),
        state: State::Gas,
    },
    Element {
        atomic_number: 2,
        name: "Helium",
        symbol: "He",
        category: Category::NobleGas,
        position: Position::MainTable { period: 1, group: 18 },
        weight: Some(4.003),
        state: State::Gas,
    },
    Element {
        atomic_number: 3,
        name: "Lithium",
        symbol: "Li",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 2, group: 1 },
        weight: Some(6.940),
        state: State::Solid,
    },
    Element {
        atomic_number: 4,
        name: "Beryllium",
        symbol: "Be",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 2, group: 2 },
        weight: Some(9.012),
        state: State::Solid,
    },
    Element {
        atomic_number: 5,
        name: "Boron",
        symbol: "B",
        category: Category::Metalloid,
        position: Position::MainTable { period: 2, group: 13 },
        weight: Some(10.810),
        state: State::Solid,
    },
    Element {
        atomic_number: 6,
        name: "Carbon",
        symbol: "C",
        category: Category::PolyatomicNonmetal,
        position: Position::MainTable { period: 2, group: 14 },
        weight: Some(12.011),
        state: State::Solid,
    },
    Element {
        atomic_number: 7,
        name: "Nitrogen",
        symbol: "N",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 2, group: 15 },
        weight: Some(14.007),
        state: State::Gas,
    },
    Element {
        atomic_number: 8,
        name: "Oxygen",
        symbol: "O",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 2, group: 16 },
        weight: Some(15.999),
        state: State::Gas,
    },
    Element {
        atomic_number: 9,
        name: "Fluorine",
        symbol: "F",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 2, group: 17 },
        weight: Some(18.998),
        state: State::Gas,
    },
    Element {
        atomic_number: 10,
        name: "Neon",
        symbol: "Ne",
        category: Category::NobleGas,
        position: Position::MainTable { period: 2, group: 18 },
        weight: Some(20.180),
        state: State::Gas,
    },
    Element {
        atomic_number: 11,
        name: "Sodium",
        symbol: "Na",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 3, group: 1 },
        weight: Some(22.990),
        state: State::Solid,
    },
    Element {
        atomic_number: 12,
        name: "Magnesium",
        symbol: "Mg",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 3, group: 2 },
        weight: Some(24.305),
        state: State::Solid,
    },
    Element {
        atomic_number: 13,
        name: "Aluminium",
        symbol: "Al",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 3, group: 13 },
        weight: Some(26.982),
        state: State::Solid,
    },
    Element {
        atomic_number: 14,
        name: "Silicon",
        symbol: "Si",
        category: Category::Metalloid,
        position: Position::MainTable { period: 3, group: 14 },
        weight: Some(28.085),
        state: State::Solid,
    },
    Element {
        atomic_number: 15,
        name: "Phosphorus",
        symbol: "P",
        category: Category::PolyatomicNonmetal,
        position: Position::MainTable { period: 3, group: 15 },
        weight: Some(30.974),
        state: State::Solid,
    },
    Element {
        atomic_number: 16,
        name: "Sulfur",
        symbol: "S",
        category: Category::PolyatomicNonmetal,
        position: Position::MainTable { period: 3, group: 16 },
        weight: Some(32.060),
        state: State::Solid,
    },
    Element {
        atomic_number: 17,
        name: "Chlorine",
        symbol: "Cl",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 3, group: 17 },
        weight: Some(35.450),
        state: State::Gas,
    },
    Element {
        atomic_number: 18,
        name: "Argon",
        symbol: "Ar",
        category: Category::NobleGas,
        position: Position::MainTable { period: 3, group: 18 },
        weight: Some(39.948),
        state: State::Gas,
    },
    Element {
        atomic_number: 19,
        name: "Potassium",
        symbol: "K",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 4, group: 1 },
        weight: Some(39.098),
        state: State::Solid,
    },
    Element {
        atomic_number: 20,
        name: "Calcium",
        symbol: "Ca",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 4, group: 2 },
        weight: Some(40.078),
        state: State::Solid,
    },
    Element {
        atomic_number: 21,
        name: "Scandium",
        symbol: "Sc",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 3 },
        weight: Some(44.956),
        state: State::Solid,
    },
    Element {
        atomic_number: 22,
        name: "Titanium",
        symbol: "Ti",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 4 },
        weight: Some(47.867),
        state: State::Solid,
    },
    Element {
        atomic_number: 23,
        name: "Vanadium",
        symbol: "V",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 5 },
        weight: Some(50.942),
        state: State::Solid,
    },
    Element {
        atomic_number: 24,
        name: "Chromium",
        symbol: "Cr",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 6 },
        weight: Some(51.996),
        state: State::Solid,
    },
    Element {
        atomic_number: 25,
        name: "Manganese",
        symbol: "Mn",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 7 },
        weight: Some(54.938),
        state: State::Solid,
    },
    Element {
        atomic_number: 26,
        name: "Iron",
        symbol: "Fe",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 8 },
        weight: Some(55.845),
        state: State::Solid,
    },
    Element {
        atomic_number: 27,
        name: "Cobalt",
        symbol: "Co",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 9 },
        weight: Some(58.933),
        state: State::Solid,
    },
    Element {
        atomic_number: 28,
        name: "Nickel",
        symbol: "Ni",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 10 },
        weight: Some(58.693),
        state: State::Solid,
    },
    Element {
        atomic_number: 29,
        name: "Copper",
        symbol: "Cu",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 11 },
        weight: Some(63.546),
        state: State::Solid,
    },
    Element {
        atomic_number: 30,
        name: "Zinc",
        symbol: "Zn",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 4, group: 12 },
        weight: Some(65.382),
        state: State::Solid,
    },
    Element {
        atomic_number: 31,
        name: "Gallium",
        symbol: "Ga",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 4, group: 13 },
        weight: Some(69.723),
        state: State::Solid,
    },
    Element {
        atomic_number: 32,
        name: "Germanium",
        symbol: "Ge",
        category: Category::Metalloid,
        position: Position::MainTable { period: 4, group: 14 },
        weight: Some(72.630),
        state: State::Solid,
    },
    Element {
        atomic_number: 33,
        name: "Arsenic",
        symbol: "As",
        category: Category::Metalloid,
        position: Position::MainTable { period: 4, group: 15 },
        weight: Some(74.922),
        state: State::Solid,
    },
    Element {
        atomic_number: 34,
        name: "Selenium",
        symbol: "Se",
        category: Category::PolyatomicNonmetal,
        position: Position::MainTable { period: 4, group: 16 },
        weight: Some(78.971),
        state: State::Solid,
    },
    Element {
        atomic_number: 35,
        name: "Bromine",
        symbol: "Br",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 4, group: 17 },
        weight: Some(79.904),
        state: State::Liquid,
    },
    Element {
        atomic_number: 36,
        name: "Krypton",
        symbol: "Kr",
        category: Category::NobleGas,
        position: Position::MainTable { period: 4, group: 18 },
        weight: Some(83.798),
        state: State::Gas,
    },
    Element {
        atomic_number: 37,
        name: "Rubidium",
        symbol: "Rb",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 5, group: 1 },
        weight: Some(85.468),
        state: State::Solid,
    },
    Element {
        atomic_number: 38,
        name: "Strontium",
        symbol: "Sr",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 5, group: 2 },
        weight: Some(87.621),
        state: State::Solid,
    },
    Element {
        atomic_number: 39,
        name: "Yttrium",
        symbol: "Y",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 3 },
        weight: Some(88.906),
        state: State::Solid,
    },
    Element {
        atomic_number: 40,
        name: "Zirconium",
        symbol: "Zr",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 4 },
        weight: Some(91.224),
        state: State::Solid,
    },
    Element {
        atomic_number: 41,
        name: "Niobium",
        symbol: "Nb",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 5 },
        weight: Some(92.906),
        state: State::Solid,
    },
    Element {
        atomic_number: 42,
        name: "Molybdenum",
        symbol: "Mo",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 6 },
        weight: Some(95.951),
        state: State::Solid,
    },
    Element {
        atomic_number: 43,
        name: "Technetium",
        symbol: "Tc",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 7 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 44,
        name: "Ruthenium",
        symbol: "Ru",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 8 },
        weight: Some(101.072),
        state: State::Solid,
    },
    Element {
        atomic_number: 45,
        name: "Rhodium",
        symbol: "Rh",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 9 },
        weight: Some(102.906),
        state: State::Solid,
    },
    Element {
        atomic_number: 46,
        name: "Palladium",
        symbol: "Pd",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 10 },
        weight: Some(106.421),
        state: State::Solid,
    },
    Element {
        atomic_number: 47,
        name: "Silver",
        symbol: "Ag",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 11 },
        weight: Some(107.868),
        state: State::Solid,
    },
    Element {
        atomic_number: 48,
        name: "Cadmium",
        symbol: "Cd",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 5, group: 12 },
        weight: Some(112.414),
        state: State::Solid,
    },
    Element {
        atomic_number: 49,
        name: "Indium",
        symbol: "In",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 5, group: 13 },
        weight: Some(114.818),
        state: State::Solid,
    },
    Element {
        atomic_number: 50,
        name: "Tin",
        symbol: "Sn",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 5, group: 14 },
        weight: Some(118.710),
        state: State::Solid,
    },
    Element {
        atomic_number: 51,
        name: "Antimony",
        symbol: "Sb",
        category: Category::Metalloid,
        position: Position::MainTable { period: 5, group: 15 },
        weight: Some(121.760),
        state: State::Solid,
    },
    Element {
        atomic_number: 52,
        name: "Tellurium",
        symbol: "Te",
        category: Category::Metalloid,
        position: Position::MainTable { period: 5, group: 16 },
        weight: Some(127.603),
        state: State::Solid,
    },
    Element {
        atomic_number: 53,
        name: "Iodine",
        symbol: "I",
        category: Category::DiatomicNonmetal,
        position: Position::MainTable { period: 5, group: 17 },
        weight: Some(126.904),
        state: State::Solid,
    },
    Element {
        atomic_number: 54,
        name: "Xenon",
        symbol: "Xe",
        category: Category::NobleGas,
        position: Position::MainTable { period: 5, group: 18 },
        weight: Some(131.293),
        state: State::Gas,
    },
    Element {
        atomic_number: 55,
        name: "Caesium",
        symbol: "Cs",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 6, group: 1 },
        weight: Some(132.905),
        state: State::Solid,
    },
    Element {
        atomic_number: 56,
        name: "Barium",
        symbol: "Ba",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 6, group: 2 },
        weight: Some(137.327),
        state: State::Solid,
    },
    Element {
        atomic_number: 57,
        name: "Lanthanum",
        symbol: "La",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 1 },
        weight: Some(138.905),
        state: State::Solid,
    },
    Element {
        atomic_number: 58,
        name: "Cerium",
        symbol: "Ce",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 2 },
        weight: Some(140.116),
        state: State::Solid,
    },
    Element {
        atomic_number: 59,
        name: "Praseodymium",
        symbol: "Pr",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 3 },
        weight: Some(140.908),
        state: State::Solid,
    },
    Element {
        atomic_number: 60,
        name: "Neodymium",
        symbol: "Nd",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 4 },
        weight: Some(144.242),
        state: State::Solid,
    },
    Element {
        atomic_number: 61,
        name: "Promethium",
        symbol: "Pm",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 5 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 62,
        name: "Samarium",
        symbol: "Sm",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 6 },
        weight: Some(150.362),
        state: State::Solid,
    },
    Element {
        atomic_number: 63,
        name: "Europium",
        symbol: "Eu",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 7 },
        weight: Some(151.964),
        state: State::Solid,
    },
    Element {
        atomic_number: 64,
        name: "Gadolinium",
        symbol: "Gd",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 8 },
        weight: Some(157.253),
        state: State::Solid,
    },
    Element {
        atomic_number: 65,
        name: "Terbium",
        symbol: "Tb",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 9 },
        weight: Some(158.925),
        state: State::Solid,
    },
    Element {
        atomic_number: 66,
        name: "Dysprosium",
        symbol: "Dy",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 10 },
        weight: Some(162.500),
        state: State::Solid,
    },
    Element {
        atomic_number: 67,
        name: "Holmium",
        symbol: "Ho",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 11 },
        weight: Some(164.930),
        state: State::Solid,
    },
    Element {
        atomic_number: 68,
        name: "Erbium",
        symbol: "Er",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 12 },
        weight: Some(167.259),
        state: State::Solid,
    },
    Element {
        atomic_number: 69,
        name: "Thulium",
        symbol: "Tm",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 13 },
        weight: Some(168.934),
        state: State::Solid,
    },
    Element {
        atomic_number: 70,
        name: "Ytterbium",
        symbol: "Yb",
        category: Category::Lanthanide,
        position: Position::Lanthanides { column: 14 },
        weight: Some(173.045),
        state: State::Solid,
    },
    Element {
        atomic_number: 71,
        name: "Lutetium",
        symbol: "Lu",
        category: Category::Lanthanide,
        position: Position::MainTable { period: 6, group: 3 },
        //position: Position::Lanthanides { column: 15 },
        weight: Some(174.967),
        state: State::Solid,
    },
    Element {
        atomic_number: 72,
        name: "Hafnium",
        symbol: "Hf",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 4 },
        weight: Some(178.492),
        state: State::Solid,
    },
    Element {
        atomic_number: 73,
        name: "Tantalum",
        symbol: "Ta",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 5 },
        weight: Some(180.948),
        state: State::Solid,
    },
    Element {
        atomic_number: 74,
        name: "Tungsten",
        symbol: "W",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 6 },
        weight: Some(183.841),
        state: State::Solid,
    },
    Element {
        atomic_number: 75,
        name: "Rhenium",
        symbol: "Re",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 7 },
        weight: Some(186.207),
        state: State::Solid,
    },
    Element {
        atomic_number: 76,
        name: "Osmium",
        symbol: "Os",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 8 },
        weight: Some(190.233),
        state: State::Solid,
    },
    Element {
        atomic_number: 77,
        name: "Iridium",
        symbol: "Ir",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 9 },
        weight: Some(192.217),
        state: State::Solid,
    },
    Element {
        atomic_number: 78,
        name: "Platinum",
        symbol: "Pt",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 10 },
        weight: Some(195.084),
        state: State::Solid,
    },
    Element {
        atomic_number: 79,
        name: "Gold",
        symbol: "Au",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 11 },
        weight: Some(196.967),
        state: State::Solid,
    },
    Element {
        atomic_number: 80,
        name: "Mercury",
        symbol: "Hg",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 6, group: 12 },
        weight: Some(200.592),
        state: State::Liquid,
    },
    Element {
        atomic_number: 81,
        name: "Thallium",
        symbol: "Tl",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 6, group: 13 },
        weight: Some(204.380),
        state: State::Solid,
    },
    Element {
        atomic_number: 82,
        name: "Lead",
        symbol: "Pb",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 6, group: 14 },
        weight: Some(207.210),
        state: State::Solid,
    },
    Element {
        atomic_number: 83,
        name: "Bismuth",
        symbol: "Bi",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 6, group: 15 },
        weight: Some(208.980),
        state: State::Solid,
    },
    Element {
        atomic_number: 84,
        name: "Polonium",
        symbol: "Po",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 6, group: 16 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 85,
        name: "Astatine",
        symbol: "At",
        category: Category::Metalloid,
        position: Position::MainTable { period: 6, group: 17 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 86,
        name: "Radon",
        symbol: "Rn",
        category: Category::NobleGas,
        position: Position::MainTable { period: 6, group: 18 },
        weight: None,
        state: State::Gas,
    },
    Element {
        atomic_number: 87,
        name: "Francium",
        symbol: "Fr",
        category: Category::AlkaliMetal,
        position: Position::MainTable { period: 7, group: 1 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 88,
        name: "Radium",
        symbol: "Ra",
        category: Category::AlkalineEarthMetal,
        position: Position::MainTable { period: 7, group: 2 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 89,
        name: "Actinium",
        symbol: "Ac",
        category: Category::Actinide,
        position: Position::Actinides { column: 1 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 90,
        name: "Thorium",
        symbol: "Th",
        category: Category::Actinide,
        position: Position::Actinides { column: 2 },
        weight: Some(232.038),
        state: State::Solid,
    },
    Element {
        atomic_number: 91,
        name: "Protactinium",
        symbol: "Pa",
        category: Category::Actinide,
        position: Position::Actinides { column: 3 },
        weight: Some(231.036),
        state: State::Solid,
    },
    Element {
        atomic_number: 92,
        name: "Uranium",
        symbol: "U",
        category: Category::Actinide,
        position: Position::Actinides { column: 4 },
        weight: Some(238.029),
        state: State::Solid,
    },
    Element {
        atomic_number: 93,
        name: "Neptunium",
        symbol: "Np",
        category: Category::Actinide,
        position: Position::Actinides { column: 5 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 94,
        name: "Plutonium",
        symbol: "Pu",
        category: Category::Actinide,
        position: Position::Actinides { column: 6 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 95,
        name: "Americium",
        symbol: "Am",
        category: Category::Actinide,
        position: Position::Actinides { column: 7 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 96,
        name: "Curium",
        symbol: "Cm",
        category: Category::Actinide,
        position: Position::Actinides { column: 8 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 97,
        name: "Berkelium",
        symbol: "Bk",
        category: Category::Actinide,
        position: Position::Actinides { column: 9 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 98,
        name: "Californium",
        symbol: "Cf",
        category: Category::Actinide,
        position: Position::Actinides { column: 10 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 99,
        name: "Einsteinium",
        symbol: "Es",
        category: Category::Actinide,
        position: Position::Actinides { column: 11 },
        weight: None,
        state: State::Solid,
    },
    Element {
        atomic_number: 100,
        name: "Fermium",
        symbol: "Fm",
        category: Category::Actinide,
        position: Position::Actinides { column: 12 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 101,
        name: "Mendelevium",
        symbol: "Md",
        category: Category::Actinide,
        position: Position::Actinides { column: 13 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 102,
        name: "Nobelium",
        symbol: "No",
        category: Category::Actinide,
        position: Position::Actinides { column: 14 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 103,
        name: "Lawrencium",
        symbol: "Lr",
        category: Category::Actinide,
        position: Position::MainTable { period: 7, group: 3 },
        //position: Position::Actinides { column: 15 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 104,
        name: "Rutherfordium",
        symbol: "Rf",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 4 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 105,
        name: "Dubnium",
        symbol: "Db",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 5 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 106,
        name: "Seaborgium",
        symbol: "Sg",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 6 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 107,
        name: "Bohrium",
        symbol: "Bh",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 7 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 108,
        name: "Hassium",
        symbol: "Hs",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 8 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 109,
        name: "Meitnerium",
        symbol: "Mt",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 9 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 110,
        name: "Darmstadtium",
        symbol: "Ds",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 10 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 111,
        name: "Roentgenium",
        symbol: "Rg",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 11 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 112,
        name: "Copernicium",
        symbol: "Cn",
        category: Category::TransitionMetal,
        position: Position::MainTable { period: 7, group: 12 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 113,
        name: "Nihonium",
        symbol: "Nh",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 13 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 114,
        name: "Flerovium",
        symbol: "Fl",
        category: Category::PostTransitionMetal,
        position: Position::MainTable { period: 7, group: 14 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 115,
        name: "Moscovium",
        symbol: "Mc",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 15 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 116,
        name: "Livermorium",
        symbol: "Lv",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 16 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 117,
        name: "Tennessine",
        symbol: "Ts",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 17 },
        weight: None,
        state: State::Unknown,
    },
    Element {
        atomic_number: 118,
        name: "Oganesson",
        symbol: "Og",
        category: Category::Unknown,
        position: Position::MainTable { period: 7, group: 18 },
        weight: None,
        state: State::Unknown,
    },
];
